language: node_js
node_js:
- '8'
services:
- docker
install:
- yarn
- yarn lint
- yarn e2e
- yarn build
- sudo apt update && sudo apt install google-chrome-stable
cache:
  yarn: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
deploy:
  provider: cloudfoundry
  api: api.run.pivotal.io
  username: david.ahern26@gmail.com
  password:
    secure: AbyN1jK76TVCqdUMh1ebQjFB+mUByZg+h2JqItpwzc/JLujXQEYU1i2EXbK7uBZySioO23HoSLz8dz6U2rSKBNjsBK8XTCcQkxmN7UX1i4v91PeVlS9ALZUV2hw3M2c4R4ISbfh/lG+aLQisCHRKAJ8g7JXppbTkL2Z+oiXLVhHIIBra+7qRZqiUixs41RnQMORWRZmLYwwYawGux1uCEZckjTYKy/H4J9iev726hzFY2h4iODYdiZivY7D9vUJ0cyakkoG8ztDg/CttFl6EyrmN5PSw7QX8I1jDVtDPgn5EIKgRfgJ1ioqv/+rQHKzKbDgNpmQSm1PQdPwi7gdQE2KRul0aHyBXKrhE8qzgMCo+HgzyfAZADBG7zg92+ArOgkdO5UNJTP71mTfUcGoobWagtFwh9Xb5jUedPHprc4YeqaInMg9F6eMqkHKiXs+i+5L/G0uRw/dQIYhOfHrxHaJLx1c0A+dZ0xUGpzIPM8+g76aE4KricawJGn4Ul96gd/KbJE3ZeFfSDwtDgZlvdjTcnIqprxRfd8S+VixDxjbQmTt11oKPngOwP+cG/vWlN8pNJY+aXPHxnPLwewkO/8MwpLtDecC0fM99GZJLCg0+Mi178OID9mPtR0fJ7CzJiyPeZY8Qj4mlPnjShm3BFX8EVndxbE3QmwPiX5zZV1k=
  organization: thor
  space: prod
  on:
    repo: el-davo/blog-ui-new
    branch: master
